platform :ios, '8.0'
use_frameworks!

target 'InstaMelody' do
  pod 'FontAwesome'
  pod 'MagicalRecord'
  pod 'DACircularProgress'
  pod 'CLTokenInputView'
  pod 'MGSwipeTableCell'
  pod 'JSQMessagesViewController'
  pod 'UIImageView-Letters'
end
